# Generated by Django 3.1.3 on 2020-11-17 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201117_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
