# Generated by Django 3.1.3 on 2020-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201128_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizprofile',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct_option',
            field=models.CharField(choices=[('B', 'b'), ('D', 'd'), ('A', 'a'), ('C', 'c')], max_length=20),
        ),
    ]
