# Generated by Django 3.1.3 on 2020-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201128_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_option',
            field=models.CharField(choices=[('B', 'b'), ('C', 'c'), ('A', 'a'), ('D', 'd')], max_length=20),
        ),
    ]
