# Generated by Django 3.1.3 on 2020-11-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_attemptedquestion_choice_question_quizprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attemptedquestion',
            old_name='quiz_Profile',
            new_name='quiz_profile',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='mark_obtained',
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Marks Obtained'),
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Was this attempt correct?'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
